;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        c-electric-brace
        c-electric-colon
        dabbrev-expand
        mc/vertical-align
        mc/vertical-align-with-space
        ))

(setq mc/cmds-to-run-once
      '(
        helm-M-x
        ))
