;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        backward-kill-sentence
        beginning-of-visual-line
        c-electric-brace
        c-electric-colon
        c-electric-lt-gt
        c-electric-paren
        c-electric-semi&comma
        c-electric-slash
        c-electric-star
        c-hungry-delete-backwards
        c-indent-line-or-region
        cargo-process-build
        dabbrev-expand
        emmet-expand-line
        end-of-visual-line
        evil-backward-char
        evil-backward-word-begin
        evil-copy-from-above
        evil-find-char
        evil-forward-char
        evil-forward-word-begin
        evil-insert
        evil-normal-state
        fill-paragraph
        ignore
        indent-for-tab-command
        indent-region
        insert-parentheses
        kill-region
        kill-visual-line
        mc/vertical-align
        mc/vertical-align-with-space
        ))

(setq mc/cmds-to-run-once
      '(
        c-electric-pound
        helm-M-x
        markdown-outdent-or-delete
        web-mode-mark-and-expand
        ))
