(deftheme misa
  "Created 2019-01-04.")

(custom-theme-set-faces
 'misa
 '(default ((t (:family "Liberation Mono" :foundry "outline" :width normal :height 90 :weight normal :slant normal :underline nil :overline nil :strike-through nil :box nil :inverse-video nil :foreground "#b4a485" :background "#042327" :stipple nil :inherit nil))))
 '(cursor ((t (:foreground "#cfdfef" :background "#708090"))))
 '(fixed-pitch ((t (:family "Monospace"))))
 '(variable-pitch ((t (:family "Arial" :foundry "outline" :width normal :height 98 :weight normal :slant normal))))
 '(escape-glyph ((((background dark)) (:foreground "cyan")) (((type pc)) (:foreground "magenta")) (t (:foreground "brown"))))
 '(homoglyph ((((background dark)) (:foreground "cyan")) (((type pc)) (:foreground "magenta")) (t (:foreground "brown"))))
 '(minibuffer-prompt ((t (:weight bold :foreground "#708090"))))
 '(highlight ((t (:background "#3857bf"))))
 '(region ((t (:background "#1837af"))))
 '(shadow ((((class color grayscale) (min-colors 88) (background light)) (:foreground "grey50")) (((class color grayscale) (min-colors 88) (background dark)) (:foreground "grey70")) (((class color) (min-colors 8) (background light)) (:foreground "green")) (((class color) (min-colors 8) (background dark)) (:foreground "yellow"))))
 '(secondary-selection ((((class color) (min-colors 88) (background light)) (:background "yellow1")) (((class color) (min-colors 88) (background dark)) (:background "SkyBlue4")) (((class color) (min-colors 16) (background light)) (:background "yellow")) (((class color) (min-colors 16) (background dark)) (:background "SkyBlue4")) (((class color) (min-colors 8)) (:foreground "black" :background "cyan")) (t (:inverse-video t))))
 '(trailing-whitespace ((((class color) (background light)) (:background "red1")) (((class color) (background dark)) (:background "red1")) (t (:inverse-video t))))
 '(font-lock-builtin-face ((t (:foreground "#cfbfad"))))
 '(font-lock-comment-delimiter-face ((t (:foreground "#eee926"))))
 '(font-lock-comment-face ((t (:foreground "#eee926"))))
 '(font-lock-constant-face ((t (:foreground "#85ecd7"))))
 '(font-lock-doc-face ((t (:foreground "#cd8b00"))))
 '(font-lock-function-name-face ((t (:foreground "#e1f4ff"))))
 '(font-lock-keyword-face ((t (:foreground "#e1f4ff"))))
 '(font-lock-negation-char-face ((t (:foreground "#C62626"))))
 '(font-lock-preprocessor-face ((t (:foreground "#ade6b3"))))
 '(font-lock-regexp-grouping-backslash ((t (:foreground "#EF7760" :inherit (bold)))))
 '(font-lock-regexp-grouping-construct ((t (:foreground "#EF7760" :inherit (bold)))))
 '(font-lock-string-face ((t (:slant italic :foreground "#36bca8"))))
 '(font-lock-type-face ((t (:foreground "#ade6b3"))))
 '(font-lock-variable-name-face ((t (:foreground "#e1f4ff"))))
 '(font-lock-warning-face ((t (:foreground "#ffffff" :background "#ff0000"))))
 '(button ((t (:underline (:color foreground-color :style line) :foreground "#8AC6F2" :inherit (link)))))
 '(link ((t (:underline (:color foreground-color :style line) :foreground "cyan1"))))
 '(link-visited ((t (:foreground "violet" :inherit (link)))))
 '(fringe ((t (:foreground "#cfbfad" :background "#042327"))))
 '(header-line ((t (:box nil :foreground "grey90" :background "grey20" :inherit (mode-line)))))
 '(tooltip ((t (:foreground "systeminfotext" :background "systeminfowindow" :inherit (variable-pitch)))))
 '(mode-line ((t (:box (:line-width -1 :color nil :style released-button) :foreground "black" :background "#28379f"))))
 '(mode-line-buffer-id ((t (:weight bold :foreground "#b9b9b9" :background "#28274f"))))
 '(mode-line-emphasis ((t (:weight bold))))
 '(mode-line-highlight ((((class color) (min-colors 88)) (:box (:line-width 2 :color "grey40" :style released-button))) (t (:inherit (highlight)))))
 '(mode-line-inactive ((t (:foreground "#708090" :background "#28274f"))))
 '(isearch ((t (:weight bold :foreground "#303030" :background "#cd8b60"))))
 '(isearch-fail ((((class color) (min-colors 88) (background light)) (:background "RosyBrown1")) (((class color) (min-colors 88) (background dark)) (:background "red4")) (((class color) (min-colors 16)) (:background "red")) (((class color) (min-colors 8)) (:background "red")) (((class color grayscale)) (:foreground "grey")) (t (:inverse-video t))))
 '(lazy-highlight ((t (:foreground "#E2DAEF" :background "paleturquoise4"))))
 '(match ((((class color) (min-colors 88) (background light)) (:background "yellow1")) (((class color) (min-colors 88) (background dark)) (:background "RoyalBlue3")) (((class color) (min-colors 8) (background light)) (:foreground "black" :background "yellow")) (((class color) (min-colors 8) (background dark)) (:foreground "white" :background "blue")) (((type tty) (class mono)) (:inverse-video t)) (t (:background "gray"))))
 '(next-error ((t (:inherit (region)))))
 '(query-replace ((t (:inherit (isearch))))))

(provide-theme 'misa)
