(deftheme test-theme
  "Created 2018-12-27.")

(custom-theme-set-faces
 'test-theme
 '(default ((t (:inherit nil :stipple nil :background "#042327" :foreground "#b4a485" :inverse-video nil :box nil :strike-through nil :overline nil :underline nil :slant normal :weight normal :height 113 :width normal :foundry "outline" :family "Liberation Mono"))))
 '(cursor ((t (:background "#708090" :foreground "#cfdfef"))))
 '(fixed-pitch ((t (:family "Monospace"))))
 '(variable-pitch ((t (:slant normal :weight normal :height 98 :width normal :foundry "outline" :family "Arial"))))
 '(escape-glyph ((((background dark)) (:foreground "cyan")) (((type pc)) (:foreground "magenta")) (t (:foreground "brown"))))
 '(homoglyph ((((background dark)) (:foreground "cyan")) (((type pc)) (:foreground "magenta")) (t (:foreground "brown"))))
 '(minibuffer-prompt ((t (:foreground "#708090" :weight bold))))
 '(highlight ((t (:background "#1837af"))))
 '(region ((t (:background "#1837af"))))
 '(shadow ((((class color grayscale) (min-colors 88) (background light)) (:foreground "grey50")) (((class color grayscale) (min-colors 88) (background dark)) (:foreground "grey70")) (((class color) (min-colors 8) (background light)) (:foreground "green")) (((class color) (min-colors 8) (background dark)) (:foreground "yellow"))))
 '(secondary-selection ((((class color) (min-colors 88) (background light)) (:background "yellow1")) (((class color) (min-colors 88) (background dark)) (:background "SkyBlue4")) (((class color) (min-colors 16) (background light)) (:background "yellow")) (((class color) (min-colors 16) (background dark)) (:background "SkyBlue4")) (((class color) (min-colors 8)) (:background "cyan" :foreground "black")) (t (:inverse-video t))))
 '(trailing-whitespace ((((class color) (background light)) (:background "red1")) (((class color) (background dark)) (:background "red1")) (t (:inverse-video t))))
 '(font-lock-builtin-face ((t (:foreground "#cfbfad"))))
 '(font-lock-comment-delimiter-face ((t (:foreground "#eee926"))))
 '(font-lock-comment-face ((t (:foreground "#eee926"))))
 '(font-lock-constant-face ((t (:foreground "#85ecd7"))))
 '(font-lock-doc-face ((t (:foreground "#cd8b00"))))
 '(font-lock-function-name-face ((t (:foreground "#e1f4ff"))))
 '(font-lock-keyword-face ((t (:foreground "#e1f4ff"))))
 '(font-lock-negation-char-face ((t (:foreground "#C62626"))))
 '(font-lock-preprocessor-face ((t (:foreground "#ade6b3"))))
 '(font-lock-regexp-grouping-backslash ((t (:foreground "#EF7760" :inherit (bold)))))
 '(font-lock-regexp-grouping-construct ((t (:foreground "#EF7760" :inherit (bold)))))
 '(font-lock-string-face ((t (:foreground "#36bca8" :slant italic))))
 '(font-lock-type-face ((t (:foreground "#ade6b3"))))
 '(font-lock-variable-name-face ((t (:foreground "#e1f4ff"))))
 '(font-lock-warning-face ((t (:background "#ff0000" :foreground "#ffffff"))))
 '(button ((t (:underline (:color foreground-color :style line) :foreground "#8AC6F2" :inherit (link)))))
 '(link ((((class color) (min-colors 88) (background light)) (:foreground "RoyalBlue3" :underline (:color foreground-color :style line))) (((class color) (background light)) (:foreground "blue" :underline (:color foreground-color :style line))) (((class color) (min-colors 88) (background dark)) (:foreground "cyan1" :underline (:color foreground-color :style line))) (((class color) (background dark)) (:foreground "cyan" :underline (:color foreground-color :style line))) (t (:inherit (underline)))))
 '(link-visited ((default (:inherit (link))) (((class color) (background light)) (:foreground "magenta4")) (((class color) (background dark)) (:foreground "violet"))))
 '(fringe ((t (:background "#042327" :foreground "#cfbfad"))))
 '(header-line ((default (:inherit (mode-line))) (((type tty)) (:inverse-video nil :underline (:color foreground-color :style line))) (((class color grayscale) (background light)) (:background "grey90" :foreground "grey20" :box nil)) (((class color grayscale) (background dark)) (:background "grey20" :foreground "grey90" :box nil)) (((class mono) (background light)) (:background "white" :foreground "black" :inverse-video nil :box nil :underline (:color foreground-color :style line))) (((class mono) (background dark)) (:background "black" :foreground "white" :inverse-video nil :box nil :underline (:color foreground-color :style line)))))
 '(tooltip ((t (:inherit (variable-pitch) :background "systeminfowindow" :foreground "systeminfotext"))))
 '(mode-line ((((class color) (min-colors 88)) (:box (:line-width -1 :color nil :style released-button) :background "grey75" :foreground "black")) (t (:inverse-video t))))
 '(mode-line-buffer-id ((t (:background "#3e3e5e" :foreground "#b9b9b9" :weight bold))))
 '(mode-line-emphasis ((t (:weight bold))))
 '(mode-line-highlight ((((class color) (min-colors 88)) (:box (:line-width 2 :color "grey40" :style released-button))) (t (:inherit (highlight)))))
 '(mode-line-inactive ((t (:background "#3e3e5e" :foreground "#708090"))))
 '(isearch ((t (:background "#cd8b60" :foreground "#303030" :weight bold))))
 '(isearch-fail ((((class color) (min-colors 88) (background light)) (:background "RosyBrown1")) (((class color) (min-colors 88) (background dark)) (:background "red4")) (((class color) (min-colors 16)) (:background "red")) (((class color) (min-colors 8)) (:background "red")) (((class color grayscale)) (:foreground "grey")) (t (:inverse-video t))))
 '(lazy-highlight ((t (:foreground "#E2DAEF" :background "paleturquoise4"))))
 '(match ((((class color) (min-colors 88) (background light)) (:background "yellow1")) (((class color) (min-colors 88) (background dark)) (:background "RoyalBlue3")) (((class color) (min-colors 8) (background light)) (:background "yellow" :foreground "black")) (((class color) (min-colors 8) (background dark)) (:background "blue" :foreground "white")) (((type tty) (class mono)) (:inverse-video t)) (t (:background "gray"))))
 '(next-error ((t (:inherit (region)))))
 '(query-replace ((t (:inherit (isearch))))))

(provide-theme 'test-theme)
